/**
 * Palworld level/EXP curve (src/data/expTable.json, regenerated by
 * scripts/gen-exp-table.mjs from palworld-save-pal's exp.json).
 *
 * `total[i]` is the cumulative EXP required to *be* player level i+1
 * (`total[0]` = 0 for level 1); `palTotal` is the same curve for Pals.
 * `cap` is the displayed level cap (80 as of Palworld 1.0) — the table runs
 * to `maxLevel` (100) but levels past `cap` are unreachable in normal play.
 */
import raw from "../data/expTable.json";

export interface ExpTable {
  /** Displayed level cap (80 in Palworld 1.0). */
  cap: number;
  /** Highest level the table covers (100). */
  maxLevel: number;
  /** Cumulative player EXP per level; total[0] = level 1 = 0. */
  total: number[];
  /** Cumulative Pal EXP per level. */
  palTotal: number[];
}

export const EXP_TABLE = raw as ExpTable;
export const LEVEL_CAP = EXP_TABLE.cap;
export const MAX_LEVEL = EXP_TABLE.maxLevel;

export interface LevelProgress {
  /** Percent (0–100) of the way from `level` to `level + 1`; 100 at maxLevel. */
  pct: number;
  /** EXP accumulated past the start of `level`. */
  into: number;
  /** EXP needed to go from `level` to `level + 1`, or null at maxLevel. */
  next: number | null;
}

/**
 * Progress toward the next level given a cumulative EXP value and the current
 * level, using the Pal curve when `pal` is true. Out-of-range levels are
 * clamped to [1, maxLevel].
 */
export function levelProgress(exp: number, level: number, pal: boolean): LevelProgress {
  const totals = pal ? EXP_TABLE.palTotal : EXP_TABLE.total;
  const lv = Math.min(Math.max(Math.trunc(level) || 1, 1), EXP_TABLE.maxLevel);
  const base = totals[lv - 1] ?? 0;
  const into = Math.max(0, exp - base);
  if (lv >= EXP_TABLE.maxLevel) return { pct: 100, into, next: null };
  const next = totals[lv] - base;
  const pct = next > 0 ? Math.min(100, (into / next) * 100) : 0;
  return { pct, into, next };
}
