/**
 * Item weight + stack lookup: maps a bridge item `static_id` to its per-unit
 * weight and max stack size, from the bundled catalog (`src/data/itemMeta.json`,
 * generated by `scripts/gen-item-meta.mjs`). The in-game inventory shows a small
 * weight number in the top-left of every slot; the UI resolves it the same way.
 */
import meta from "../data/itemMeta.json";

const META = meta as Record<string, { weight: number; stack: number }>;

/** Per-unit weight for an item `static_id`, or 0 if unknown. */
export function itemWeight(staticId: string): number {
  return META[staticId]?.weight ?? 0;
}

/** Max stack size for an item `static_id`, or 0 if unknown. */
export function itemStack(staticId: string): number {
  return META[staticId]?.stack ?? 0;
}
