/**
 * Passive-skill ranks + disabled-content lists (src/data/skillMeta.json,
 * regenerated by scripts/gen-skill-meta.mjs from a palworld-save-pal checkout).
 *
 * Ranks drive the colored left border on passive-skill picker rows (the same
 * palette palworld-save-pal uses); the disabled lists hide unreleased/internal
 * content from the item and passive pickers.
 */
import raw from "../data/skillMeta.json";

export interface SkillMeta {
  /** Passive code → rank (negative = detrimental, 1 = common, up to 4–5 rare). */
  passiveRank: Record<string, number>;
  disabledItems: string[];
  disabledPassives: string[];
  disabledPals: string[];
}

export const SKILL_META = raw as SkillMeta;

export const DISABLED_ITEMS = new Set(SKILL_META.disabledItems);
export const DISABLED_PASSIVES = new Set(SKILL_META.disabledPassives);
export const DISABLED_PALS = new Set(SKILL_META.disabledPals);

/** Rank for a passive code; unknown codes read as rank 0 (neutral). */
export function passiveRank(code: string): number {
  return SKILL_META.passiveRank[code] ?? 0;
}

/**
 * Rank → accent color, ported from palworld-save-pal:
 * negative = red, 1 (and 0/unknown) = neutral, 2–3 = gold, 4+ = teal.
 */
export function passiveRankColor(rank: number): string {
  if (rank < 0) return "#ec6a6a";
  if (rank >= 4) return "#68ffd8";
  if (rank >= 2) return "#fcdf19";
  return "#62646c";
}
